import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../../lib/utils";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // optional: create a CSS variable for it
  weight: ["400", "700"], // optional: choose font weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        <Providers>
          <main className="relative flex flex-col min-h-screen">
            <Navbar></Navbar>

            <div className="flex-grow flex-1">{children}</div>
          </main>

          <Toaster position="top-center" richColors />
        </Providers>
      </body>
    </html>
  );
}
